import { commercialRecord, type VendorRecord } from "./types";

export const bidWritingSoftwareRecords: readonly VendorRecord[] = [
  commercialRecord({
    slug: "autogenai", name: "AutogenAI", category: "bid-writing-software",
    providerType: "AI-assisted proposal and RFP software", officialUrl: "https://autogenai.com/",
    summary: "AutogenAI offers proposal drafting, content reuse and RFP management for enterprise, federal and grant teams.",
    coverage: "Global commercial and public-sector proposal use, with a separate US federal offer.",
    pricing: "No public numeric price published on the checked provider pages. Book a demo for a quote.",
    pricingCaveat: "Ask for implementation, model usage, users, storage, support and renewal costs separately.",
    bestFor: "Organisations with recurring complex proposals and enough approved content for a governed workspace.",
    notFor: "Occasional bidders needing a low-cost self-serve writing tool.",
    caveat: "Provider performance figures are not independently tested. Generated content still needs evidence and human review.",
    evidenceLinks: [{ label: "AutogenAI product scope", url: "https://autogenai.com/" }],
  }),
  commercialRecord({
    slug: "loopio", name: "Loopio", category: "bid-writing-software",
    providerType: "RFP response and content-management software", officialUrl: "https://loopio.com/",
    summary: "Loopio supports RFP, RFI, due-diligence and security-questionnaire responses with libraries and projects.",
    coverage: "Global response teams; integrations and multilingual features depend on plan or add-on.",
    pricing: "Foundations: starts at $20,000/year and includes 10 seats. Enhanced and Enterprise: custom quote.",
    pricingCaveat: "Translations, onboarding and integrations may be add-ons. Confirm currency, taxes and renewal uplift.",
    bestFor: "Teams handling frequent questionnaires and maintaining a controlled answer library.",
    notFor: "Small occasional bidders with no content owner or library-maintenance process.",
    caveat: "Autofill depends on current approved content and does not replace subject-matter review.",
    evidenceLinks: [{ label: "Loopio plans", url: "https://loopio.com/pricing/" }],
  }),
  commercialRecord({
    slug: "responsive", name: "Responsive", category: "bid-writing-software",
    providerType: "Strategic response-management software", officialUrl: "https://www.responsive.io/",
    summary: "Responsive manages RFPs, RFIs, due-diligence questionnaires, security questionnaires and reusable content.",
    coverage: "Global enterprise response use; packages and professional services vary by workflow.",
    pricing: "No public numeric price published on the checked package pages. Contact the provider.",
    pricingCaveat: "Ask which products, users, business units, integrations, migration and services are included.",
    bestFor: "Large teams coordinating content owners, reviewers and several questionnaire types.",
    notFor: "A bidder needing simple drafting without a managed knowledge base.",
    caveat: "Package descriptions include products and add-ons. Match the order form to the tested workflow.",
    evidenceLinks: [{ label: "Responsive package capabilities", url: "https://www.responsive.io/product-packages/standard" }],
  }),
  commercialRecord({
    slug: "qorusdocs", name: "QorusDocs", category: "bid-writing-software",
    providerType: "Microsoft 365 proposal-management software", officialUrl: "https://www.qorusdocs.com/",
    summary: "QorusDocs supports proposals, pitches, presentations and RFP responses inside Microsoft 365 workflows.",
    coverage: "Global professional-services, legal and technology teams; built around Microsoft 365.",
    pricing: "No public numeric price published on the checked provider page. Request a demo and quote.",
    pricingCaveat: "Confirm Microsoft prerequisites, user basis, implementation, templates and integrations.",
    bestFor: "Microsoft 365 proposal teams needing branded content and controlled collaboration.",
    notFor: "Teams without Microsoft 365 or those seeking tender discovery.",
    caveat: "The provider says content stays in the customer's Microsoft environment. Verify architecture and data terms.",
    evidenceLinks: [{ label: "QorusDocs platform and security scope", url: "https://www.qorusdocs.com/" }],
  }),
  commercialRecord({
    slug: "inventive-ai", name: "Inventive AI", category: "bid-writing-software",
    providerType: "Usage-priced RFP and questionnaire software", officialUrl: "https://www.inventive.ai/",
    summary: "Inventive AI combines RFP and security-questionnaire workflows with a knowledge hub and integrations.",
    coverage: "Global B2B response use, with file and knowledge-source integrations listed by the provider.",
    pricing: "Plans start at $10,000/year. Pricing combines a platform fee with usage per RFP or security questionnaire.",
    pricingCaveat: "Users are stated as unlimited. Obtain the usage table, rollover rules and platform fee in the quote.",
    bestFor: "Teams preferring usage-based pricing over per-seat licensing.",
    notFor: "A buyer needing a fixed public total without discussing RFP volume.",
    caveat: "Accuracy claims are provider-stated. Require citations and human approval for material answers.",
    evidenceLinks: [{ label: "Inventive AI pricing", url: "https://www.inventive.ai/inventive-ai-pricing" }],
  }),
  commercialRecord({
    slug: "xaitporter", name: "XaitPorter", category: "bid-writing-software",
    providerType: "Co-authoring and proposal-production software", officialUrl: "https://www.xait.com/",
    summary: "XaitPorter supports concurrent writing, role access, structured documents, reuse and automated formatting.",
    coverage: "Global enterprise use, particularly complex proposals, tenders, reports and regulated documents.",
    pricing: "No public numeric price published on the checked provider pages. Request a custom quote.",
    pricingCaveat: "Confirm users, storage, implementation, AI, API and any XaitCPQ integration cost.",
    bestFor: "Teams co-authoring large technical tenders with strict document control.",
    notFor: "Occasional bidders who only need short-form text drafting.",
    caveat: "Time-saving claims are provider-stated. Trial final exports and the permission model.",
    evidenceLinks: [{ label: "Xait product overview", url: "https://www.xait.com/" }],
  }),
  commercialRecord({
    slug: "conveyor", name: "Conveyor", category: "bid-writing-software",
    providerType: "Security questionnaire and RFP automation software", officialUrl: "https://www.conveyor.com/",
    summary: "Conveyor combines a trust centre with questionnaire automation and limited RFP projects on paid plans.",
    coverage: "Global customer-trust, security questionnaire and RFP use cases.",
    pricing: "Free trust-centre plan: $0. Business: starts at $9,600/year with usage credits and 10 RFP projects.",
    pricingCaveat: "Free excludes questionnaire automation and integrations. Paid usage is credit-based.",
    bestFor: "Security and sales teams whose RFP work overlaps with customer trust reviews.",
    notFor: "General bid teams that do not handle security questionnaires or need unlimited projects.",
    caveat: "The provider distinguishes security questionnaires from general RFPs. Confirm fit for your document mix.",
    evidenceLinks: [{ label: "Conveyor pricing", url: "https://www.conveyor.com/pricing" }],
  }),
  commercialRecord({
    slug: "ombud", name: "Ombud", category: "bid-writing-software",
    providerType: "Automated response and knowledge-management software", officialUrl: "https://www.ombud.com/",
    summary: "Ombud manages knowledge and responses to RFPs, RFIs, due-diligence and security questionnaires.",
    coverage: "Global B2B response and revenue teams.",
    pricing: "No public numeric price published on the checked provider page. Contact the provider.",
    pricingCaveat: "Request implementation, migration, users, integrations, AI usage and support costs.",
    bestFor: "Teams needing a central answer repository alongside response automation.",
    notFor: "A company without owners and review dates for reusable content.",
    caveat: "Automated answers depend on approved, current source material and human review.",
    evidenceLinks: [{ label: "Ombud product overview", url: "https://www.ombud.com/product/overview" }],
  }),
  commercialRecord({
    slug: "stotles-bid-studio", name: "Stotles Bid Studio", category: "bid-writing-software",
    providerType: "Tender qualification and bid-response software", officialUrl: "https://www.stotles.com/pricing",
    summary: "Stotles lists bid or no-bid reports, tender tracking, bid projects, a content library and generated responses.",
    coverage: "Public-sector bid teams using Stotles market data and their own bid content.",
    pricing: "Basic: £0 with three bid or no-bid reports. Growth: from £495/month. Expert: custom price.",
    pricingCaveat: "Growth has monthly report and project allowances. Confirm users, storage and limits.",
    bestFor: "UK public-sector teams wanting qualification and response workflow connected to tender data.",
    notFor: "Teams seeking a standalone general-purpose proposal designer.",
    caveat: "Generated responses and scores are not buyer evaluations. Check evidence and compliance.",
    evidenceLinks: [{ label: "Stotles Bid Studio plans", url: "https://www.stotles.com/pricing" }],
  }),
  commercialRecord({
    slug: "bidscript", name: "BidScript", category: "bid-writing-software",
    providerType: "UK bid-management and response software", officialUrl: "https://www.bidscript.ai/",
    summary: "BidScript covers opportunity discovery, qualification, submission tracking, collaboration and reusable response content.",
    coverage: "The provider positions the product for UK mid-market bid and proposal teams handling RFPs and tenders.",
    pricing: "No public numeric price published on the checked provider pages. Request a demo and quote.",
    pricingCaveat: "Ask for users, discovery coverage, content migration, model usage, integrations, support and renewal terms.",
    bestFor: "UK in-house teams wanting bid workflow and content reuse in one product.",
    notFor: "Occasional bidders seeking a simple document editor with a public price.",
    caveat: "Performance figures on the site are provider-stated. Validate permissions, citations and final exports on a real bid.",
    evidenceLinks: [{ label: "BidScript product scope", url: "https://www.bidscript.ai/" }],
  }),
  commercialRecord({
    slug: "tendereyes", name: "TenderEyes", category: "bid-writing-software",
    providerType: "Enterprise bid-management software", officialUrl: "https://tendereyessoftware.com/",
    summary: "TenderEyes supports planning, collaboration, approvals, compliance, content and performance views across the bid lifecycle.",
    coverage: "The provider describes global enterprise use for tender and proposal teams.",
    pricing: "No public numeric price published on the checked provider pages. Book a demo for a quote.",
    pricingCaveat: "Confirm modules, users, implementation, migration, integrations, security options and support.",
    bestFor: "Established bid teams needing structured governance across many contributors.",
    notFor: "Small teams looking for a lightweight self-serve writing assistant.",
    caveat: "Product outcomes are provider-stated. Test the approval trail and document output before purchase.",
    evidenceLinks: [{ label: "TenderEyes solution overview", url: "https://tendereyessoftware.com/solution-overview/" }],
  }),
  commercialRecord({
    slug: "mytender-io", name: "mytender.io", category: "bid-writing-software",
    providerType: "UK tender-writing and bid-workflow software", officialUrl: "https://mytender.io/",
    summary: "mytender.io offers tender-document analysis, a bid library, response drafting, collaboration and pipeline views.",
    coverage: "The provider lists integrations with SharePoint, Salesforce, Google Drive, HubSpot and other business systems.",
    pricing: "No public numeric price published on the checked provider page. Request a demo and quote.",
    pricingCaveat: "Ask for users, documents, model usage, integrations, onboarding, data location and renewal terms.",
    bestFor: "UK work-winning teams with reusable evidence and several live tenders.",
    notFor: "A team seeking verified outcome claims or an official tender portal.",
    caveat: "Speed and outcome figures are provider claims. Generated responses need evidence checks and accountable review.",
    evidenceLinks: [{ label: "mytender.io product scope", url: "https://mytender.io/" }],
  }),
  commercialRecord({
    slug: "brainial", name: "Brainial", category: "bid-writing-software",
    providerType: "European tender-analysis and management software", officialUrl: "https://brainial.com/",
    summary: "Brainial analyses tender documents, identifies requirements and risks, and provides source references through the bid cycle.",
    coverage: "The provider describes use by tender teams across Europe and sector-specific workflows.",
    pricing: "No public numeric price published on the checked official pages. Book a demo for a quote.",
    pricingCaveat: "Confirm users, supported languages, document limits, integrations, onboarding, hosting and renewal terms.",
    bestFor: "European teams that prioritise requirement extraction and traceable risk review.",
    notFor: "Teams that only want opportunity alerts or a published self-serve price.",
    caveat: "Time-saving and quality claims are provider-stated. Check extracted requirements against the complete tender pack.",
    evidenceLinks: [{ label: "Brainial tender-management scope", url: "https://brainial.com/" }],
  }),
  commercialRecord({
    slug: "altura", name: "Altura", category: "bid-writing-software",
    providerType: "European complex-bid management software", officialUrl: "https://altura.io/en",
    summary: "Altura structures requirements, risks, qualification, response work and collaboration for multi-stakeholder bids.",
    coverage: "Starter, Professional and Advanced plans include different seats, workflows, permissions and onboarding.",
    pricing: "Starter, Professional and Advanced: price on request. All plans use annual subscriptions.",
    pricingCaveat: "Pricing depends on team size and use. The checked page lists 3, 5 and 10 core seats respectively, with plan-specific collaborators.",
    bestFor: "European bid teams managing complex tenders with several reviewers and contributors.",
    notFor: "A small bidder needing immediate self-serve access and a public numeric price.",
    caveat: "Output validation and performance claims are provider-stated. Review source links and compliance checks yourself.",
    evidenceLinks: [{ label: "Altura pricing and plan scope", url: "https://altura.io/en/pricing" }],
  }),
  commercialRecord({
    slug: "tendium-bidflow", name: "Tendium BidFlow", category: "bid-writing-software",
    providerType: "European tender-monitoring and bid-workflow software", officialUrl: "https://tendium.com/",
    summary: "Tendium BidFlow supports qualification, checklists, project work, a content library and response writing alongside tender monitoring.",
    coverage: "Core and Scale add BidFlow to monitoring; intelligence add-ons are currently stated for Sweden, Norway and Finland.",
    pricing: "Light monitoring: from €125/month. Core and Scale with BidFlow: contact sales.",
    pricingCaveat: "Unlimited users are stated. Core and Scale pricing varies with bid volume; confirm countries, add-ons and billing term.",
    bestFor: "European public-sector sales teams wanting discovery and bid workflow in one service.",
    notFor: "UK-only teams assuming Nordic intelligence add-ons cover their market.",
    caveat: "Market coverage and generated content are provider-stated. Check official notices and review every response.",
    evidenceLinks: [{ label: "Tendium pricing and BidFlow features", url: "https://tendium.com/pricing" }],
  }),
  commercialRecord({
    slug: "bidwell-writing", name: "Bidwell", category: "bid-writing-software",
    providerType: "UK tender discovery and writing suite", officialUrl: "https://bidwell.app/",
    summary: "Bidwell combines opportunity matching with tender analysis, drafting, a knowledge base and document export.",
    coverage: "The provider positions the writing tools for UK public-sector bids and connects them to its discovery module.",
    pricing: "Discover: £15/month. Draft: £30/month. Full Suite: £40/month. A seven-day trial is advertised.",
    pricingCaveat: "Confirm current module limits, users, model usage, VAT, export formats and annual billing before purchase.",
    bestFor: "UK SMEs wanting discovery and assisted drafting in one low-cost account.",
    notFor: "Large proposal teams that need complex permissions, approvals and enterprise integrations.",
    caveat: "Generated answers, fit scores and source coverage are provider claims. Review every response against the tender pack and approved evidence.",
    evidenceLinks: [{ label: "Bidwell product suite", url: "https://bidwell.app/" }, { label: "Bidwell discovery module", url: "https://bidwell.app/product/discover" }],
  }),
  commercialRecord({
    slug: "tenderdraft", name: "TenderDraft", category: "bid-writing-software",
    providerType: "Prelaunch UK AI tender-writing software", officialUrl: "https://tenderdraft.overpass.co.uk/",
    summary: "TenderDraft advertises document analysis, response drafting, a company profile vault, a content library and DOCX export.",
    coverage: "The provider positions the product for UK tender responses and social-value content.",
    pricing: "Proposed waitlist plans: Starter £49/month, Professional £99/month and Team £179/month.",
    pricingCaveat: "The product is not generally available. Treat the published feature set and pricing as provisional until launch.",
    bestFor: "UK bid teams evaluating a future self-serve drafting tool with reusable company evidence.",
    notFor: "Teams that need a production-ready product, contracted service levels or proven exports today.",
    caveat: "UK procurement policy does not approve any specific AI product. Suppliers remain responsible for disclosure, accuracy, confidentiality and the submitted bid.",
    evidenceLinks: [{ label: "TenderDraft waitlist and proposed plans", url: "https://tenderdraft.overpass.co.uk/" }, { label: "PPN 017 on AI use in procurement", url: "https://www.gov.uk/government/publications/ppn-017-improving-transparency-of-ai-use-in-procurement/ppn-017-improving-transparency-of-ai-use-in-procurement-html" }],
  }),
] as const;
