import { commercialRecord, type VendorRecord } from "./types";

export const bidWritingServiceRecords: readonly VendorRecord[] = [
  commercialRecord({
    slug: "thornton-and-lowe", name: "Thornton & Lowe", category: "bid-writing-services",
    providerType: "UK bid-writing and bid-management consultancy", officialUrl: "https://thorntonandlowe.com/",
    summary: "Services include writing, review, management, training, social value and recurring bid support.",
    coverage: "UK public-sector and commercial tenders across multiple industries, mainly delivered remotely.",
    pricing: "Review from £450. Typical fixed fee £1,500 to £4,000. Complex bids can exceed £20,000. Day rates £450 to £750.",
    pricingCaveat: "Final price follows review of the tender pack; ongoing monthly packages have separate scopes.",
    bestFor: "UK organisations choosing between review, fixed-fee work, day rate or retained support.",
    notFor: "A bidder wanting a fixed outcome guarantee or someone else to set its commercial price.",
    caveat: "The consultancy states that bid pricing remains the client's responsibility.",
    evidenceLinks: [{ label: "Thornton & Lowe services and fees", url: "https://thorntonandlowe.com/services/bid-writing/" }],
  }),
  commercialRecord({
    slug: "executive-compass", name: "Executive Compass", category: "bid-writing-services",
    providerType: "UK bid and tender consultancy", officialUrl: "https://www.executivecompass.co.uk/",
    summary: "Executive Compass offers tender writing, management, review, pre-bid consultancy and interim support.",
    coverage: "UK and international work across owner-managed firms, SMEs and larger organisations.",
    pricing: "No public price list. Fixed project quote after document review; retainers are available.",
    pricingCaveat: "Price depends on word count, work days, meetings, research and data collation.",
    bestFor: "Bidders wanting a project-specific fixed quote and managed quality response.",
    notFor: "Suppliers seeking outsourced commercial pricing or a public tariff.",
    caveat: "The provider does not advise on the bidder's commercial price and may decline same-tender conflicts.",
    evidenceLinks: [{ label: "Executive Compass services", url: "https://www.executivecompass.co.uk/services/bid-and-tender-writing/" }],
  }),
  commercialRecord({
    slug: "hudson-succeed", name: "Hudson Succeed", category: "bid-writing-services",
    providerType: "Bid-writing and proposal consultancy", officialUrl: "https://www.tenderconsultants.co.uk/",
    summary: "Hudson Succeed offers fixed-fee writing, management, review, bid readiness and library or policy support.",
    coverage: "UK and international delivery through the wider Hudson organisation.",
    pricing: "No current numeric public rate. The current service page offers a fixed-fee quote after review.",
    pricingCaveat: "Older brochures have numeric prices; obtain a dated quote rather than treating them as a current tariff.",
    bestFor: "Organisations needing quality-response writing, submission support or bid readiness.",
    notFor: "Suppliers wanting outsourced commercial pricing or a current public rate card.",
    caveat: "The current writing page focuses on the quality response. Confirm responsibility for cost schedules and approvals.",
    evidenceLinks: [{ label: "Hudson Succeed current writing service", url: "https://www.tenderconsultants.co.uk/bid-writing-services/" }],
  }),
  commercialRecord({
    slug: "bid-perfect", name: "Bid Perfect", category: "bid-writing-services",
    providerType: "International bid-support and training consultancy", officialUrl: "https://www.bidperfect.com/",
    summary: "Bid Perfect supplies bid directors, managers, writers, reviewers, designers, editors and training.",
    coverage: "UK and international assignments; the provider describes work across 19 countries.",
    pricing: "No public numeric writing rate. The provider states a day-and-expense charging basis.",
    pricingCaveat: "Clients review proposed personnel and may interview them. Bid Perfect does not offer no-win-no-fee work.",
    bestFor: "Organisations with temporary resource gaps or complex bids needing several specialist roles.",
    notFor: "A buyer seeking outcome-contingent fees or one uniform directly employed team.",
    caveat: "This is primarily an associate and interim-resource model. Confirm named people, days and reviews.",
    evidenceLinks: [{ label: "Bid Perfect support and fee basis", url: "https://www.bidperfect.com/bid-support-services/" }],
  }),
  commercialRecord({
    slug: "strategic-proposals", name: "Strategic Proposals", category: "bid-writing-services",
    providerType: "Bid and proposal consultancy and training provider", officialUrl: "https://strategicproposals.com/",
    summary: "Services span capture, management, writing, design, reviews, rebids, training and process improvement.",
    coverage: "Global work with operations in the UK, US, Canada and the Netherlands.",
    pricing: "No public numeric consultancy or writing price published on the checked pages.",
    pricingCaveat: "Request a scope separating consulting, writing, reviews, training, travel and expenses.",
    bestFor: "Established proposal teams handling complex pursuits or improving capability.",
    notFor: "Small suppliers requiring a low-cost transactional writing service.",
    caveat: "The offer extends beyond tender completion. Confirm whether the engagement supplies writers, reviewers or coaches.",
    evidenceLinks: [{ label: "Strategic Proposals services", url: "https://strategicproposals.com/about-us-uk/our-services" }],
  }),
  commercialRecord({
    slug: "bid-solutions", name: "Bid Solutions", category: "bid-writing-services",
    providerType: "Independent bid-consultant network", officialUrl: "https://bidsolutions.com/",
    summary: "Bid Solutions matches clients with independent writers, managers, capture specialists and designers.",
    coverage: "Full UK coverage with consultants also available worldwide.",
    pricing: "Published averages: bid writers £600/day and bid managers £659/day. Directory ranges vary by role and engagement.",
    pricingCaveat: "Rates vary by industry, location, duration and consultant; directory ranges assume a typical three-month contract.",
    bestFor: "Organisations needing a specific role, background, clearance, location or urgent capacity.",
    notFor: "Buyers expecting one directly employed team under a single house method.",
    caveat: "Delivery is through independent consultants. Review the named person's CV, references and availability.",
    evidenceLinks: [{ label: "Bid Solutions consulting and rates", url: "https://bidsolutions.com/bid-consulting/" }],
  }),
  commercialRecord({
    slug: "shipley-uk", name: "Shipley UK", category: "bid-writing-services",
    providerType: "Capture, bid and proposal consultancy", officialUrl: "https://www.shipleywins.co.uk/",
    summary: "Shipley UK offers capture, bid management, writing, editing, visual strategy, coaching and training.",
    coverage: "UK delivery with a wider international Shipley office network.",
    pricing: "No public numeric consulting or writing rate published on the checked pages.",
    pricingCaveat: "For international work, confirm the contracting entity, delivery office, people and expenses.",
    bestFor: "Technical, regulated, defence or infrastructure pursuits needing capture through proposal support.",
    notFor: "Buyers wanting a simple publicly priced copyedit.",
    caveat: "The service is method-led and may include coaching and capability transfer. Define the concrete deliverables.",
    evidenceLinks: [{ label: "Shipley opportunity consulting", url: "https://www.shipleywins.co.uk/bid-services/opportunity-consulting/" }],
  }),
  commercialRecord({
    slug: "the-bid-team", name: "The Bid Team", category: "bid-writing-services",
    providerType: "Bid strategy, writing and design consultancy", officialUrl: "https://www.thebidteam.com/",
    summary: "The Bid Team offers pre-bid positioning, direction, management, writing, graphics, review and managed support.",
    coverage: "UK and international tender work across public and private sectors.",
    pricing: "No public numeric writing or consultancy rate published on the checked pages.",
    pricingCaveat: "Ask for the roles, planned days, drafts, design, reviews, expenses and submission responsibility.",
    bestFor: "Complex or high-value submissions requiring coordinated strategy, writing, review and design.",
    notFor: "Organisations expecting an external writer to replace internal subject-matter experts.",
    caveat: "The provider states that clients supply sector expertise. Evidence and solution ownership remain with the bidder.",
    evidenceLinks: [{ label: "The Bid Team services", url: "https://www.thebidteam.com/services/" }],
  }),
  commercialRecord({
    slug: "tenders-uk", name: "Tenders UK", category: "bid-writing-services",
    providerType: "Tender-writing and bid-management consultancy", officialUrl: "https://www.tenders-uk.com/",
    summary: "Tenders UK offers writing, end-to-end management, strategy, evaluation, training and portal submission.",
    coverage: "Primarily UK public procurement, with international work also described by the provider.",
    pricing: "Full-team writing projects typically start around £4,500; fixed fee varies by questions, words and complexity.",
    pricingCaveat: "The published starting figure is indicative, not a tariff for every bid.",
    bestFor: "UK suppliers wanting a full team, particularly in the provider's published sector areas.",
    notFor: "Buyers seeking a public line-item tariff for small writing tasks.",
    caveat: "The provider says it writes opportunity-specific content. The client still must supply accurate evidence.",
    evidenceLinks: [{ label: "Tenders UK services", url: "https://www.tenders-uk.com/" }],
  }),
  commercialRecord({
    slug: "tender-response", name: "Tender Response", category: "bid-writing-services",
    providerType: "UK tender support and opportunity service", officialUrl: "https://www.tenderresponse.co.uk/",
    summary: "Services include finding, qualification, reading, writing, PQQ or SQ responses, portal and policy support.",
    coverage: "UK public-sector and charity procurement only.",
    pricing: "No numeric Tender Writer fee published. The FAQ says Tender Reader and Tender Writer use a fixed fee.",
    pricingCaveat: "Tender Finder subscriptions are separate and should not be treated as writing fees.",
    bestFor: "UK SMEs, charities and first-time public-sector bidders needing partial or complete support.",
    notFor: "International tenders or suppliers seeking advice on the price they should bid.",
    caveat: "The provider explicitly says it cannot advise on the bidder's pricing structure or expected winning price.",
    evidenceLinks: [{ label: "Tender Response writing service", url: "https://www.tenderresponse.co.uk/services/bid-support-services/tender-writer/" }],
  }),
] as const;

