import { officialRecord, type VendorRecord } from "./types";

export const officialPortalRecords: readonly VendorRecord[] = [
  officialRecord({
    slug: "find-a-tender", name: "Find a Tender", category: "official-portals",
    providerType: "UK central digital platform and notice service", officialUrl: "https://www.find-tender.service.gov.uk/",
    summary: "Find a Tender is the UK-wide service for regulated notices and the central digital platform for supplier information.",
    coverage: "UK notices in scope of the service, supplier registration and reusable core information.",
    pricing: "Free to search, register and use. Official guidance says there are no charges to view opportunities.",
    pricingCaveat: "A notice may direct suppliers to another e-sourcing portal for documents, questions or submission.",
    bestFor: "Every supplier monitoring UK regulated procurement or needing a PPON supplier identifier.",
    notFor: "Replacing every devolved, low-value or buyer-specific submission portal.",
    caveat: "Follow the individual notice. Registration, core information and submission are separate steps.",
    evidenceLinks: [{ label: "Find a Tender service", url: "https://www.find-tender.service.gov.uk/" }],
  }),
  officialRecord({
    slug: "contracts-finder", name: "Contracts Finder", category: "official-portals",
    providerType: "Official England contract-opportunity service", officialUrl: "https://www.contractsfinder.service.gov.uk/contractfinder",
    summary: "Contracts Finder publishes opportunities, early-engagement notices and awards from public bodies in England.",
    coverage: "England-focused contracts; official guidance points to devolved portals and Find a Tender for other coverage.",
    pricing: "Free to search without an account. A free account enables saved searches and email updates.",
    pricingCaveat: "Threshold and publication rules differ by authority and regime. Check linked tender documents.",
    bestFor: "Suppliers monitoring English public opportunities, including lower-value notices and awards.",
    notFor: "Complete coverage of Scotland, Wales, Northern Ireland or every e-sourcing event.",
    caveat: "The notice may link elsewhere for documents and submission. The live buyer instructions control.",
    evidenceLinks: [{ label: "GOV.UK Contracts Finder guidance", url: "https://www.gov.uk/contracts-finder" }],
  }),
  officialRecord({
    slug: "public-contracts-scotland", name: "Public Contracts Scotland", category: "official-portals",
    providerType: "Official Scottish procurement notice portal", officialUrl: "https://www.publiccontractsscotland.gov.uk/",
    summary: "Public Contracts Scotland publishes Scottish opportunities, awards, contracts and some subcontract notices.",
    coverage: "Scottish public bodies, including high and low-value opportunities and a contracts register.",
    pricing: "Supplier registration is free, including search and regular email alerts.",
    pricingCaveat: "Some exercises use Public Contracts Scotland Tender or another linked workspace for response.",
    bestFor: "Suppliers targeting Scottish public bodies and Scottish low-value or subcontract opportunities.",
    notFor: "A complete UK-wide search on its own.",
    caveat: "Subcontract notices are business-to-business transactions and carry a specific portal disclaimer.",
    evidenceLinks: [{ label: "Free supplier registration", url: "https://www.publiccontractsscotland.gov.uk/register/register_start.aspx" }],
  }),
  officialRecord({
    slug: "sell2wales", name: "Sell2Wales", category: "official-portals",
    providerType: "Welsh Government procurement portal", officialUrl: "https://www.sell2wales.gov.wales/",
    summary: "Sell2Wales publishes Welsh notices and supports alerts, supplier profiles, quick quotes and responses.",
    coverage: "Welsh Government, councils, NHS bodies, education and other Welsh public organisations.",
    pricing: "Free for buyers and suppliers; free registration provides search, alerts and portal tools.",
    pricingCaveat: "Suppliers may need a central digital platform identifier and must follow each notice.",
    bestFor: "Suppliers targeting Welsh public-sector and advertised subcontract opportunities.",
    notFor: "Complete UK coverage without Find a Tender and other national portals.",
    caveat: "Invitation-only Quick Quotes require an invitation. Registration does not guarantee one.",
    evidenceLinks: [{ label: "Sell2Wales service overview", url: "https://www.sell2wales.gov.wales/AboutUs/AboutUs_Main.aspx" }],
  }),
  officialRecord({
    slug: "etendersni", name: "eTendersNI", category: "official-portals",
    providerType: "Official Northern Ireland e-tendering portal", officialUrl: "https://etendersni.gov.uk/epps/home.do",
    summary: "eTendersNI advertises and manages opportunities for Northern Ireland departments, agencies and public bodies.",
    coverage: "Northern Ireland public procurement, including events not necessarily required on Find a Tender.",
    pricing: "No supplier charge to view opportunities; registration is required to respond and receive notifications.",
    pricingCaveat: "Complete registration and software requirements before a live deadline.",
    bestFor: "Suppliers pursuing Northern Ireland public-sector contracts.",
    notFor: "A complete UK view without the other national services.",
    caveat: "Some notices also appear on Find a Tender; other eTendersNI events may only appear locally.",
    evidenceLinks: [{ label: "eTendersNI supplier home", url: "https://etendersni.gov.uk/epps/home.do" }],
  }),
  officialRecord({
    slug: "defence-sourcing-portal", name: "Defence Sourcing Portal", category: "official-portals",
    providerType: "UK Ministry of Defence e-sourcing portal", officialUrl: "https://contracts.mod.uk/",
    summary: "The Defence Sourcing Portal advertises and manages Ministry of Defence contracting opportunities.",
    coverage: "UK defence opportunities, tendering activity, communications and supply-chain notices.",
    pricing: "Supplier portal access and registration are free; no public supplier subscription fee is stated.",
    pricingCaveat: "Some processes require separate security, finance or identity steps stated in the procurement.",
    bestFor: "Suppliers targeting direct or supply-chain work with UK Defence.",
    notFor: "General public-sector coverage outside defence.",
    caveat: "Registration does not establish eligibility. Read the security and submission conditions.",
    evidenceLinks: [{ label: "MOD e-procurement guidance", url: "https://www.gov.uk/government/publications/mod-contracting-purchasing-and-finance-e-procurement-system" }],
  }),
  officialRecord({
    slug: "nhs-atamis", name: "NHS Atamis", category: "official-portals",
    providerType: "NHS health-family e-commercial system", officialUrl: "https://health-family.force.com/s/Welcome",
    summary: "NHS England describes Atamis as the system used by the large majority of NHS organisations for procurement.",
    coverage: "A large majority of NHS organisations in England, including tender events and Evergreen assessment.",
    pricing: "No supplier registration fee is stated. NHS England says no prerequisites are required before registering.",
    pricingCaveat: "Not every NHS route is in one system. Also monitor Contracts Finder and Find a Tender.",
    bestFor: "Prospective suppliers to NHS organisations using the health-family system.",
    notFor: "All UK healthcare procurement without checking local, devolved and Supply Chain routes.",
    caveat: "NHS buying is decentralised. The responsible organisation and notice determine the actual portal.",
    evidenceLinks: [{ label: "NHS England Atamis guidance", url: "https://www.england.nhs.uk/nhs-commercial/nhs-england-procurement/" }],
  }),
  officialRecord({
    slug: "ted", name: "Tenders Electronic Daily", category: "official-portals",
    providerType: "Official EU procurement notice service", officialUrl: "https://ted.europa.eu/",
    summary: "TED is the online Supplement to the Official Journal of the European Union for procurement notices.",
    coverage: "EU and associated public procurement notices, with search and open-data services.",
    pricing: "Free public search and data access. eNotices2 for buyer publication is also a free service.",
    pricingCaveat: "TED is often the publication layer; documents and responses may sit on a national portal.",
    bestFor: "Suppliers monitoring regulated procurement across EU and associated markets.",
    notFor: "A complete view of below-threshold local opportunities in every country.",
    caveat: "Follow the notice to authority documents and the submission route, and check amendments.",
    evidenceLinks: [{ label: "TED open-data service", url: "https://data.ted.europa.eu/" }],
  }),
  officialRecord({
    slug: "ungm", name: "United Nations Global Marketplace", category: "official-portals",
    providerType: "Official UN procurement gateway", officialUrl: "https://www.ungm.org/",
    summary: "UNGM is the common platform used by UN organisations for registration, opportunities and awards.",
    coverage: "Participating UN organisations and international bodies across countries and sectors.",
    pricing: "Supplier registration and opportunity browsing are free. UNGM Pro is an optional paid subscription.",
    pricingCaveat: "Core registration does not automatically send every relevant opportunity; search or alerts are still needed.",
    bestFor: "Suppliers and consultants pursuing UN-system opportunities worldwide.",
    notFor: "A supplier expecting one submission method across all UN organisations.",
    caveat: "Participation methods vary between integrated systems, email and hard-copy submission.",
    evidenceLinks: [{ label: "UNGM free and Pro comparison", url: "https://www.ungm.org/Public/UNGMPro" }],
  }),
  officialRecord({
    slug: "world-bank-procurement-notices", name: "World Bank Procurement Notices", category: "official-portals",
    providerType: "Official World Bank project-procurement service", officialUrl: "https://projects.worldbank.org/en/projects-operations/procurement",
    summary: "The World Bank publishes notices and business opportunities for Bank-financed projects.",
    coverage: "Current, upcoming and potential opportunities across financed projects and countries.",
    pricing: "Free public search, Excel download and email-alert subscription are offered.",
    pricingCaveat: "Borrowers run the procurement; documents and submissions may use another named channel.",
    bestFor: "Consultants, contractors and suppliers pursuing World Bank-financed projects.",
    notFor: "Vendors seeking only the World Bank Group's own corporate purchasing events.",
    caveat: "Potential opportunities are indicative and may change or not proceed. Current notices control.",
    evidenceLinks: [{ label: "World Bank opportunity stages", url: "https://projects.worldbank.org/en/projects-operations/opportunities" }],
  }),
] as const;

