import { commercialRecord, type VendorRecord } from "./types";

export const procurementIntelligenceRecords: readonly VendorRecord[] = [
  commercialRecord({
    slug: "bidskim-intelligence", name: "BidSkim", category: "procurement-intelligence",
    providerType: "Commercial procurement-intelligence platform", officialUrl: "https://bidskim.com/",
    summary: "BidSkim says its higher plan connects tenders with renewal signals, buyer profiles, competitor awards and similar contracts.",
    coverage: "Provider states Britain-wide data from Find a Tender, Contracts Finder, Public Contracts Scotland and Sell2Wales.",
    pricing: "Free: £0. Monitor: £79/month or £780/year. Predict: £189/month or £1,860/year.",
    pricingCaveat: "These plan names and annual prices were supplied by BidSkim Limited on 12 August 2026. The public page may still show older annual amounts or terminology.",
    bestFor: "Small British suppliers linking current notices to buyer and contract context.",
    notFor: "Large teams needing enterprise account management or markets outside Great Britain.",
    caveat: "Renewal dates can be observed, calculated or predictive signals. Verify the source and status before acting.",
    evidenceLinks: [{ label: "BidSkim pricing and scope", url: "https://bidskim.com/pricing" }],
  }),
  commercialRecord({
    slug: "stotles-sales-studio", name: "Stotles Sales Studio", category: "procurement-intelligence",
    providerType: "Commercial UK public-sector sales platform", officialUrl: "https://www.stotles.com/",
    summary: "Stotles lists tenders, pre-tenders, expiring contracts, buyer and supplier profiles, frameworks and contacts by tier.",
    coverage: "Provider describes UK portal aggregation and deeper buyer, supplier, framework and document data on paid plans.",
    pricing: "Free: £0/month. Basic: headline from £75/month. Growth: from £475/month. Expert: custom price.",
    pricingCaveat: "The checked Stotles page is internally inconsistent on Basic pricing, also showing other figures in comparison content. Confirm the current checkout price. Features vary by tier.",
    bestFor: "UK public-sector sales teams building account plans and routes-to-market.",
    notFor: "A supplier needing only the authoritative submission portal.",
    caveat: "Forecast expiries and buyer signals need source review. Ask how each signal is derived and updated.",
    evidenceLinks: [{ label: "Stotles pricing", url: "https://www.stotles.com/pricing" }],
  }),
  commercialRecord({
    slug: "tussell", name: "Tussell", category: "procurement-intelligence",
    providerType: "Commercial UK public-sector market-intelligence platform", officialUrl: "https://www.tussell.com/",
    summary: "Tussell says it standardises UK tenders, awards, frameworks, spending and contacts for market analysis.",
    coverage: "UK public procurement, with plan-dependent early opportunities, FOI requests, contacts, API and integrations.",
    pricing: "No public numeric price. Annual quote varies by business size, term, tier and add-ons.",
    pricingCaveat: "Starter, Plus and Pro are described publicly, but an accurate quote requires a sales call.",
    bestFor: "Established UK teams needing award, spend, framework and buyer analysis.",
    notFor: "A supplier seeking only a low-cost self-serve tender alert.",
    caveat: "Tussell states that it is not an e-procurement, bid-management or bid-writing tool.",
    evidenceLinks: [{ label: "Tussell plans and caveats", url: "https://www.tussell.com/plans" }],
  }),
  commercialRecord({
    slug: "spend-network", name: "Spend Network", category: "procurement-intelligence",
    providerType: "Commercial global procurement-data provider", officialUrl: "https://www.spendnetwork.com/",
    summary: "Spend Network says it collects and enhances tender, contract, spend and grant data for applications and analysis.",
    coverage: "Provider states more than 700 feeds worldwide, with web application, API and white-label options.",
    pricing: "No public numeric price published on the checked provider page. Book a demo for a quote.",
    pricingCaveat: "Request a data dictionary, source list, refresh terms, licence rights and API limits with the quote.",
    bestFor: "Data teams, exporters and consultancies needing global procurement datasets or an API.",
    notFor: "A small supplier looking only for a simple UK daily alert.",
    caveat: "Global feed counts do not establish completeness in a market. Validate a target-country sample.",
    evidenceLinks: [{ label: "Spend Network data scope", url: "https://www.spendnetwork.com/" }],
  }),
  commercialRecord({
    slug: "tenderalpha", name: "TenderAlpha", category: "procurement-intelligence",
    providerType: "Government-contract and supply-chain data platform", officialUrl: "https://www.tenderalpha.com/",
    summary: "TenderAlpha combines government contract awards, company intelligence and stated G2B and B2B transaction data.",
    coverage: "Provider describes global government-contract and private supply-chain datasets.",
    pricing: "No public numeric price published on the checked provider pages. Contact the provider.",
    pricingCaveat: "Ask which datasets, countries, history, exports and reuse rights are included.",
    bestFor: "Research or enterprise teams connecting procurement and company data across markets.",
    notFor: "A supplier that only needs UK tender emails.",
    caveat: "Scale and uniqueness claims are not independently tested here. Request sample records for your market.",
    evidenceLinks: [{ label: "TenderAlpha platform", url: "https://www.tenderalpha.com/platform/" }],
  }),
  commercialRecord({
    slug: "govtribe", name: "GovTribe", category: "procurement-intelligence",
    providerType: "Commercial US government-contracting platform", officialUrl: "https://govtribe.com/",
    summary: "GovTribe offers opportunity and award search, buyer and vendor profiles, capture tools, contacts and integrations.",
    coverage: "Plans cover US federal data or federal plus state and local data.",
    pricing: "Federal plus state and local: Launch Plus $1,900/year; Growth Plus $6,000/year; Scale custom.",
    pricingCaveat: "Advanced AI and MCP usage is billed separately in credits. A seven-day trial is advertised.",
    bestFor: "US contractors needing opportunity, award and capture data in one workflow.",
    notFor: "Suppliers focused only on UK public procurement.",
    caveat: "Coverage, seats, exports and AI-credit allowances differ by plan.",
    evidenceLinks: [{ label: "GovTribe plans", url: "https://govtribe.com/plans" }],
  }),
  commercialRecord({
    slug: "highergov", name: "HigherGov", category: "procurement-intelligence",
    providerType: "Commercial US government-market platform", officialUrl: "https://www.highergov.com/",
    summary: "HigherGov lists market intelligence, forecasts, opportunities, pipelines, people data, exports and API access.",
    coverage: "US federal, state and local government markets.",
    pricing: "Starter: $500/year for one user. Standard: $2,500/year for up to 10. Leader: $5,000/year for up to 50.",
    pricingCaveat: "Export quantities and support differ by plan. Confirm current terms on the live page.",
    bestFor: "US contractors wanting published annual prices and broad market tools.",
    notFor: "Teams needing UK or European procurement coverage.",
    caveat: "Listed tools are provider-stated. Test source depth and recency in target agencies.",
    evidenceLinks: [{ label: "HigherGov plans", url: "https://www.highergov.com/pricing/" }],
  }),
  commercialRecord({
    slug: "govspend", name: "GovSpend", category: "procurement-intelligence",
    providerType: "US public-sector procurement-data platform", officialUrl: "https://govspend.com/",
    summary: "GovSpend says it combines bids, contracts, purchase orders, supplier context and public-meeting intelligence.",
    coverage: "US federal plus state, local and education markets through GovSpend and Fedmine products.",
    pricing: "No public numeric price published on the checked provider pages. Request a demo and quote.",
    pricingCaveat: "Ask which modules, history, exports, integrations and users are included.",
    bestFor: "US sellers or public buyers researching purchases, incumbents and upcoming demand.",
    notFor: "UK-only suppliers or anyone needing an immediate self-serve price.",
    caveat: "Dataset sizes and predictive signals are provider claims. Validate records for named agencies.",
    evidenceLinks: [{ label: "GovSpend platform overview", url: "https://govspend.com/" }],
  }),
  commercialRecord({
    slug: "deltek-govwin-iq", name: "Deltek GovWin IQ", category: "procurement-intelligence",
    providerType: "Analyst-supported government-market platform", officialUrl: "https://www.deltek.com/products/govwin/",
    summary: "Deltek says GovWin IQ combines public data, analyst-tracked opportunities, budgets, awards and contacts.",
    coverage: "US federal, state, local and education markets, plus Canadian packages.",
    pricing: "No public subscription price published on the checked product pages. Request a demo and quote.",
    pricingCaveat: "Subscriptions and data types vary by market. Ask for exact analyst, source and export scope.",
    bestFor: "Established North American government contractors with formal business-development teams.",
    notFor: "Small UK suppliers seeking a low-cost tender feed.",
    caveat: "Analyst access and early-opportunity claims are provider-stated. Define deliverables in the agreement.",
    evidenceLinks: [{ label: "GovWin IQ overview", url: "https://www.deltek.com/products/govwin/" }],
  }),
  commercialRecord({
    slug: "civant", name: "Civant", category: "procurement-intelligence",
    providerType: "European procurement-forecasting platform", officialUrl: "https://civant.eu/",
    summary: "Civant says plans include live-country coverage, buyer history, tender forecasting and market monitoring.",
    coverage: "All live countries are included; the provider does not price by country in its public description.",
    pricing: "Vanguard and Summit: price not publicly stated. Custom: annual contract and bespoke pricing.",
    pricingCaveat: "Request numeric prices, seats, alert capacity, competitor context and rollout support.",
    bestFor: "European teams comparing buyer history and future-demand monitoring across countries.",
    notFor: "Buyers requiring a published self-serve price or official submission portal.",
    caveat: "Forecasts are not confirmed procurements. Review the evidence and confidence behind each prediction.",
    evidenceLinks: [{ label: "Civant plan descriptions", url: "https://civant.eu/pricing" }],
  }),
  commercialRecord({
    slug: "bidstats-insights", name: "BidStats Insights", category: "procurement-intelligence",
    providerType: "UK procurement-intelligence subscription", officialUrl: "https://bidstats.uk/",
    summary: "BidStats Insights adds pre-procurement leads, spend, frameworks, decision-maker contacts, exports and API connectivity to its tender data.",
    coverage: "The provider states data from more than 3,000 buyers and up to ten years of tender and award history.",
    pricing: "Insights: from £5,000/year.",
    pricingCaveat: "The price is a starting figure. Confirm VAT, users, data history, contacts, API limits and service scope.",
    bestFor: "UK teams that need intelligence and data access beyond standard tender alerts.",
    notFor: "Suppliers seeking only free tender search or a submission portal.",
    caveat: "Pre-procurement leads and contacts are provider-stated. Check recency and source traceability in a sample.",
    evidenceLinks: [{ label: "BidStats Insights pricing and scope", url: "https://alpha-app.bidstats.uk/pricing" }],
  }),
  commercialRecord({
    slug: "d3-tenders-intelligence", name: "D3 Tenders", category: "procurement-intelligence",
    providerType: "UK tender and pipeline-intelligence platform", officialUrl: "https://d3tenders.com/",
    summary: "D3 Tenders combines matched notices with pipeline, buyer, supplier and market-intelligence features.",
    coverage: "The checked pricing FAQ names Contracts Finder, Find a Tender, Public Contracts Scotland and Sell2Wales.",
    pricing: "Eligible charities, VCSEs, CICs and suppliers before their first win: free Scale access. Essentials: £79/month, billed £948 yearly. Growth: £240/month. Scale: £360/month. Managed: from £840/month.",
    pricingCaveat: "The checked plan information lists up to 25 users. Confirm eligibility, billing term, VAT and managed-service scope.",
    bestFor: "UK teams wanting market context and opportunity pipeline in the same product as alerts.",
    notFor: "Research that requires confirmed eTendersNI coverage without further checking.",
    caveat: "The provider claims every UK portal, but eTendersNI is not named in its checked source FAQ.",
    evidenceLinks: [{ label: "D3 Tenders pricing and source FAQ", url: "https://d3tenders.com/pricing/" }],
  }),
  commercialRecord({
    slug: "psip-intelligence", name: "PSIP", category: "procurement-intelligence",
    providerType: "UK contract-intelligence platform", officialUrl: "https://psip.co.uk/",
    summary: "PSIP combines tender search with buyer spend, contract-expiry, incumbent, competitor and framework tools by plan.",
    coverage: "The provider names Find a Tender, Contracts Finder, Public Contracts Scotland, Sell2Wales and eTendersNI.",
    pricing: "Essential: £199/month or £169/month billed annually. Growth: £599/month or £499/month billed annually. Professional: £1,199/month or £992/month billed annually. Agency and Enterprise: custom.",
    pricingCaveat: "Prices exclude VAT. Data history, incumbent and competitor tools, exports and integrations vary by plan.",
    bestFor: "UK suppliers wanting source-linked contract context inside their qualification workflow.",
    notFor: "Teams needing decision-maker contact lists or markets outside the UK.",
    caveat: "Scores and intelligence are provider-stated. Check official records before using them in a bid decision.",
    evidenceLinks: [{ label: "PSIP pricing and feature table", url: "https://psip.co.uk/pricing" }],
  }),
  commercialRecord({
    slug: "cfp-analytics", name: "CFP Analytics", category: "procurement-intelligence",
    providerType: "UK and Ireland procurement-analytics dashboards", officialUrl: "https://www.contractfinderpro.com/products/analytics",
    summary: "CFP Analytics provides eight dashboards for opportunity, buyer, supplier, regional and industry analysis.",
    coverage: "UK and Ireland public procurement data, with filters for source, stage, value, duration, location and CPV code.",
    pricing: "No separate public numeric price for Analytics. Contract Finder Pro Core starts at £690/year plus VAT.",
    pricingCaveat: "The provider says Analytics can be added to Core and is best used alongside it. Request a module-specific quote.",
    bestFor: "UK and Ireland teams researching buyer behaviour and competitor relationships.",
    notFor: "A supplier wanting a standalone price without a sales conversation.",
    caveat: "Dashboard findings depend on the underlying sources and matching. Validate named buyers and suppliers.",
    evidenceLinks: [{ label: "CFP Analytics scope", url: "https://www.contractfinderpro.com/products/analytics" }, { label: "Contract Finder Pro pricing", url: "https://www.contractfinderpro.com/pricing" }],
  }),
  commercialRecord({
    slug: "tracker-intelligence-market", name: "Tracker Intelligence", category: "procurement-intelligence",
    providerType: "UK public-sector market-intelligence platform", officialUrl: "https://www.trackerintelligence.com/",
    summary: "Tracker combines live tenders, upcoming frameworks, historical awards, spend analytics and buyer insights.",
    coverage: "The provider describes UK public-sector data, wider European coverage and plan-dependent contacts, market leads and API access.",
    pricing: "No public numeric subscription price on the checked overview pages. Demo and short trial options are advertised.",
    pricingCaveat: "Request the exact modules, markets, users, history, exports, contacts, implementation and term in the quote.",
    bestFor: "Established suppliers that want historic market research alongside current opportunities.",
    notFor: "Teams requiring a self-serve price or only an authoritative notice portal.",
    caveat: "Dataset counts and outcome claims are provider-stated. Test source links and entity matching on known records.",
    evidenceLinks: [{ label: "Tracker platform overview", url: "https://www.trackerintelligence.com/" }, { label: "Tracker public-sector scope", url: "https://www.trackerintelligence.com/public-sector-procurement/" }],
  }),
  commercialRecord({
    slug: "oscar-research", name: "Oscar Research", category: "procurement-intelligence",
    providerType: "UK public-sector organisation and stakeholder data service", officialUrl: "https://www.oscar-research.co.uk/",
    summary: "Oscar Research provides UK public-service organisation, structure, role, contact and supplier data products.",
    coverage: "The provider describes public bodies and services across central, regional and local UK government.",
    pricing: "No public numeric subscription price found on the checked official materials. Contact the provider.",
    pricingCaveat: "Ask for covered organisations, role definitions, update frequency, licence rights, exports and suppression handling.",
    bestFor: "Teams mapping UK public bodies, structures and relevant stakeholder roles.",
    notFor: "Suppliers needing only live tender alerts or bid-writing workflow.",
    caveat: "Contact and organisation records change. Sample named target bodies and verify lawful outreach use.",
    evidenceLinks: [{ label: "Oscar Research public-sector data summary", url: "https://cat.oscar-research.co.uk/oscarinonepage.pdf" }],
  }),
  commercialRecord({
    slug: "tenderledger-intelligence", name: "TenderLedger", category: "procurement-intelligence",
    providerType: "UK contract-renewal and supplier-intelligence platform", officialUrl: "https://tenderledger.co.uk/",
    summary: "TenderLedger adds incumbent, award, buyer-pattern and estimated renewal context to UK tender monitoring.",
    coverage: "The provider names all five national UK procurement sources and says notices are deduplicated and tagged.",
    pricing: "Starter: £99/month or £990/year. Pro: £249/month or £2,490/year. Enterprise: custom.",
    pricingCaveat: "A 14-day trial is advertised. Confirm seats, source refresh, data history, exports and integrations.",
    bestFor: "UK suppliers using award and incumbent data for capture and renewal planning.",
    notFor: "Teams that require invoice-level spend analytics or official tender submission.",
    caveat: "Renewal signals are estimates derived from published records, not buyer-confirmed procurement dates.",
    evidenceLinks: [{ label: "TenderLedger pricing and renewal scope", url: "https://tenderledger.co.uk/pricing" }],
  }),
] as const;
