import { commercialRecord, type VendorRecord } from "./types";
import { tenderAlertResearchBySlug } from "./tender-alert-research";

const tenderAlertBaseRecords: readonly VendorRecord[] = [
  commercialRecord({
    slug: "bidskim-alerts", name: "BidSkim", category: "tender-alerts",
    providerType: "Commercial alert and qualification platform", officialUrl: "https://bidskim.com/",
    summary: "BidSkim says it scores public-sector notices against a supplier profile and sends a daily shortlist with reasons.",
    coverage: "Provider states Britain-wide coverage from Find a Tender, Contracts Finder, Public Contracts Scotland and Sell2Wales.",
    pricing: "Free: £0. Monitor: £79/month or £780/year. Predict: £189/month or £1,860/year.",
    pricingCaveat: "Plan names and prices were checked against BidSkim's public pricing page. Civensa and BidSkim have the same operator; see the ownership disclosure.",
    bestFor: "British suppliers wanting profile-based qualification and links back to official notices.",
    notFor: "Teams needing managed bid writing or coverage outside Great Britain.",
    caveat: "The provider says it does not write bids. Its score is a qualification aid, not a buyer decision or award forecast.",
    evidenceLinks: [{ label: "BidSkim pricing and plan scope", url: "https://bidskim.com/pricing" }],
  }),
  commercialRecord({
    slug: "stotles", name: "Stotles", category: "tender-alerts",
    providerType: "Commercial public-sector sales and bid-intelligence suite", officialUrl: "https://www.stotles.com/",
    summary: "Stotles connects tender matching with buyer documents, profiles, awards, expiries, competitor intelligence and bid workflow.",
    coverage: "The provider names the national UK portals, TED and Digital Marketplace and claims more than 100 sources.",
    pricing: "Alert entry: Sales Studio Free at £0. Full connected package: B2G Growth Engine from £873/month. Intermediate Sales and Bid Studio tiers start from £99 and £495/month.",
    pricingCaveat: "The live pricing page contains conflicting older Basic prices. Confirm included users, limits, billing term, VAT and implementation in a dated order form.",
    bestFor: "Teams wanting buyer-intent documents, entity-level market intelligence and bid workflow in one connected suite.",
    notFor: "Buyers seeking a simple low-cost alert product with fully fixed higher-tier pricing.",
    caveat: "Public corpus, coverage and AI claims are provider-stated. Expiry and relevance signals still require human validation.",
    evidenceLinks: [{ label: "Stotles pricing", url: "https://www.stotles.com/pricing" }, { label: "Stotles data", url: "https://www.stotles.com/data" }],
  }),
  commercialRecord({
    slug: "tussell", name: "Tussell", category: "tender-alerts",
    providerType: "Commercial UK procurement-intelligence platform", officialUrl: "https://www.tussell.com/",
    summary: "Tussell combines tenders with resolved buyer and supplier intelligence, awards, frameworks, renewals and verified early-opportunity signals.",
    coverage: "The provider claims monitoring across more than 600 portals and the full UK procurement cycle.",
    pricing: "Alert package: quote only. Full Pro package: quote only. Starter, Plus and Pro are annual subscriptions; Early Opportunities, API and Salesforce access vary by tier or add-on.",
    pricingCaveat: "No numeric price, user allowance or add-on price is public. Require an itemised quote for alerts and the full intelligence package.",
    bestFor: "Established UK public-sector sales teams needing curated market, competitor, framework and pre-procurement intelligence.",
    notFor: "Small suppliers requiring transparent self-serve pricing or built-in bid writing.",
    caveat: "The provider explicitly says it is not bid-management or AI bid-writing software. The complete source register is not public.",
    evidenceLinks: [{ label: "Tussell plans", url: "https://www.tussell.com/plans" }, { label: "Tussell Early Opportunities", url: "https://www.tussell.com/products/tussell-early-opportunities" }],
  }),
  commercialRecord({
    slug: "bidstats", name: "BidStats", category: "tender-alerts",
    providerType: "Commercial tender search and alert service", officialUrl: "https://bidstats.uk/",
    summary: "BidStats offers tender search, award history, daily alerts and, on higher plans, exports and pre-procurement data.",
    coverage: "Provider lists the top three portals on Standard and data from more than 3,000 buyers on higher tiers.",
    pricing: "Free: £0. Standard: £350/year. Pro: £800/year for three seats. Insights: from £5,000/year.",
    pricingCaveat: "Extra users are listed at £150 plus VAT; monthly options are advertised for Standard and Pro.",
    bestFor: "UK suppliers wanting searchable notice history with a published entry price.",
    notFor: "Teams assuming every source, export and history feature is in the free tier.",
    caveat: "Source count, history depth, exports and alert capacity differ materially by plan.",
    evidenceLinks: [{ label: "BidStats plans", url: "https://alpha-app.bidstats.uk/pricing" }],
  }),
  commercialRecord({
    slug: "tenderlake", name: "Tenderlake", category: "tender-alerts",
    providerType: "Commercial tender-intelligence platform", officialUrl: "https://www.tenderlake.com/",
    summary: "Tenderlake says it uses a supplier capability description to find and explain tenders across languages.",
    coverage: "Provider states UK, EU and EEA coverage, wider international data, translation and renewal views.",
    pricing: "No public numeric price published on the checked provider page. Demo and free-trial requests are offered.",
    pricingCaveat: "Request a quote stating countries, users, integrations, data rights and renewal terms.",
    bestFor: "Teams monitoring several European markets or distributing opportunities internally.",
    notFor: "A supplier requiring an immediate self-serve price.",
    caveat: "Coverage and match explanations are provider-stated. Test them against known notices in each target language.",
    evidenceLinks: [{ label: "Tenderlake product scope", url: "https://www.tenderlake.com/" }],
  }),
  commercialRecord({
    slug: "supply2gov", name: "Supply2Gov", category: "tender-alerts",
    providerType: "Commercial tender-alert service", officialUrl: "https://www.supply2govtenders.co.uk/",
    summary: "Supply2Gov markets weekday tender alerts and supplier support for public and private opportunities.",
    coverage: "Published plan covers the UK and Republic of Ireland and refers to CompeteFor opportunities.",
    pricing: "Free Local: £0. Country: £25/month or £270/year. UK Wide: £80/month or £799/year. UK and Ireland: £95/month or £899/year.",
    pricingCaveat: "The checked prices exclude VAT. Confirm alert profiles, users, renewal terms and included support in writing.",
    bestFor: "Suppliers seeking a managed alert profile across the UK and Ireland.",
    notFor: "Teams wanting a free nationwide aggregation tier.",
    caveat: "The provider makes broad coverage claims. Validate them with notices from portals important to you.",
    evidenceLinks: [{ label: "Supply2Gov plans", url: "https://www.supply2govtenders.co.uk/pricing-3/" }],
  }),
  commercialRecord({
    slug: "tracker-intelligence-alerts", name: "Tracker Intelligence", category: "tender-alerts",
    providerType: "Commercial tender and business-intelligence service", officialUrl: "https://www.trackerintelligence.com/",
    summary: "Tracker says it combines tender alerts with market leads, market intelligence and spend analysis.",
    coverage: "Provider describes public-sector contracts and private-sector leads; exact sources depend on service.",
    pricing: "No public subscription price published on the checked provider pages. A short Premier trial is advertised.",
    pricingCaveat: "Ask for sources, alert profiles, users, term, exports and setup charges in the quote.",
    bestFor: "Teams wanting tender alerts beside broader market and spend views.",
    notFor: "A buyer requiring a simple self-serve price comparison.",
    caveat: "Product names and included modules vary. Put the exact data scope in the order form.",
    evidenceLinks: [{ label: "Tracker platform overview", url: "https://www.trackerintelligence.com/" }],
  }),
  commercialRecord({
    slug: "mytenders-supplier", name: "myTenders", category: "tender-alerts",
    providerType: "Tender publication portal with supplier search", officialUrl: "https://www.mytenders.co.uk/",
    summary: "myTenders gives suppliers free access to notices published through its buyer portal and offers alerts.",
    coverage: "Limited to notices published through myTenders; the provider points to Tenders Direct for wider aggregation.",
    pricing: "Supplier registration and use of myTenders: free. No public price found for optional alert add-ons.",
    pricingCaveat: "Free access does not mean coverage of every UK procurement source.",
    bestFor: "Suppliers supplementing official searches with notices issued through myTenders.",
    notFor: "Anyone treating it as a complete UK-wide alert feed.",
    caveat: "The provider explicitly limits its free opportunity search to notices published through its portal.",
    evidenceLinks: [{ label: "myTenders supplier scope", url: "https://www.mytenders.co.uk/" }],
  }),
  commercialRecord({
    slug: "kimonbids-alerts", name: "KimonBids", category: "tender-alerts",
    providerType: "Commercial UK tender and bid platform", officialUrl: "https://kimonbids.com/",
    summary: "KimonBids combines search and alerts with qualification, bid drafting and intelligence on higher tiers.",
    coverage: "Provider states coverage of four UK tender portals.",
    pricing: "Free: £0. Pro: £79/month. Higher tiers are shown on the provider's live pricing table.",
    pricingCaveat: "Draft credits, buyer intelligence and compliance tools vary by tier. Check the live table.",
    bestFor: "UK SMEs comparing discovery and writing features in one product.",
    notFor: "Teams wanting a discovery-only product with no bundled writing features.",
    caveat: "Coverage, scoring and drafting claims are provider-stated and have not been tested by Civensa.",
    evidenceLinks: [{ label: "KimonBids pricing", url: "https://kimonbids.com/pricing" }],
  }),
  commercialRecord({
    slug: "d3-tenders-alerts", name: "D3 Tenders", category: "tender-alerts",
    providerType: "Commercial UK tender-alert and pipeline platform", officialUrl: "https://d3tenders.com/",
    summary: "D3 Tenders combines matched alerts, pipeline management and market-intelligence features for UK public contracts.",
    coverage: "The provider claims every UK portal, while its checked pricing FAQ names Contracts Finder, Find a Tender, Public Contracts Scotland and Sell2Wales.",
    pricing: "Eligible charities, VCSEs, CICs and suppliers before their first win: free Scale access. Essentials: £79/month, billed £948 yearly. Growth: £240/month. Scale: £360/month. Managed: from £840/month.",
    pricingCaveat: "The checked plan information lists up to 25 users. Confirm eligibility, billing term, VAT and any managed-service scope.",
    bestFor: "UK teams wanting alerts and a shared opportunity pipeline under one subscription.",
    notFor: "Suppliers that require confirmed Northern Ireland source coverage without checking first.",
    caveat: "The provider's named-source FAQ does not mention eTendersNI, despite its broader coverage claim.",
    evidenceLinks: [{ label: "D3 Tenders pricing and source FAQ", url: "https://d3tenders.com/pricing/" }],
  }),
  commercialRecord({
    slug: "psip-alerts", name: "PSIP", category: "tender-alerts",
    providerType: "Commercial UK contract-intelligence platform", officialUrl: "https://psip.co.uk/",
    summary: "PSIP provides saved tender alerts, stated relevance scores and, on higher plans, buyer, incumbent and pipeline tools.",
    coverage: "Find a Tender, Contracts Finder, Public Contracts Scotland, Sell2Wales and eTendersNI, according to the provider.",
    pricing: "Essential: £199/month or £169/month billed annually. Growth: £599/month or £499/month billed annually. Professional: £1,199/month or £992/month billed annually. Agency and Enterprise: custom.",
    pricingCaveat: "Prices exclude VAT. Alert frequency, saved searches, history, export and integrations vary by plan.",
    bestFor: "UK suppliers wanting all five national sources plus qualification and account context.",
    notFor: "Teams seeking a free ongoing plan or a submission portal.",
    caveat: "Scores and intelligence are provider-stated. Follow the original notice and review the source behind each decision.",
    evidenceLinks: [{ label: "PSIP pricing and coverage", url: "https://psip.co.uk/pricing" }],
  }),
  commercialRecord({
    slug: "contract-finder-pro-alerts", name: "Contract Finder Pro", category: "tender-alerts",
    providerType: "Commercial UK and Ireland tender-monitoring service", officialUrl: "https://www.contractfinderpro.com/",
    summary: "Contract Finder Pro offers tailored alerts, historical search and plan-dependent competitor, buyer and framework tools.",
    coverage: "The provider says it covers Find a Tender and more than 200 UK and Ireland portals, including local and sector sources.",
    pricing: "Basic: £690/year plus VAT. Professional: £990/year plus VAT. Enterprise: from £1,960/year plus VAT.",
    pricingCaveat: "A 14-day trial is advertised. Users, analytics, Tender Ninja and account support differ by tier.",
    bestFor: "UK and Ireland suppliers wanting broad portal aggregation and a yearly price.",
    notFor: "Teams that only need the five national official feeds.",
    caveat: "A large source count does not prove completeness. Test known local and sector portals before subscribing.",
    evidenceLinks: [{ label: "Contract Finder Pro pricing and coverage", url: "https://www.contractfinderpro.com/pricing" }],
  }),
  commercialRecord({
    slug: "tenders-direct-alerts", name: "Tenders Direct", category: "tender-alerts",
    providerType: "Commercial UK and EU tender-alert service", officialUrl: "https://www.tendersdirect.co.uk/",
    summary: "Tenders Direct offers personalised alerts, tender and award search, and a bid-management tool.",
    coverage: "The provider describes UK and EU coverage with more than seven years of contract and award records.",
    pricing: "Tender-alert subscriptions: from £1,359/year. Bid-writing training: from £159/course. Bid support: tailored fees.",
    pricingCaveat: "The headline is a starting price. Confirm VAT, users, alert profiles, included tools and renewal terms.",
    bestFor: "Suppliers wanting tailored alerts alongside historical UK and EU records.",
    notFor: "A small supplier requiring a free or low-cost self-serve plan.",
    caveat: "Coverage and alert accuracy are provider claims. Check matched notices against your important official sources.",
    evidenceLinks: [{ label: "Tenders Direct pricing", url: "https://www.tendersdirect.co.uk/pricing/" }, { label: "Tenders Direct alert scope", url: "https://www.tendersdirect.co.uk/product/" }],
  }),
  commercialRecord({
    slug: "tenderledger-alerts", name: "TenderLedger", category: "tender-alerts",
    providerType: "Commercial UK tender and renewal-intelligence platform", officialUrl: "https://tenderledger.co.uk/",
    summary: "TenderLedger combines tender alerts with award, incumbent, buyer and contract-renewal context.",
    coverage: "The provider names Find a Tender, Contracts Finder, Public Contracts Scotland, Sell2Wales and eTendersNI.",
    pricing: "Starter: £99/month or £990/year. Pro: £249/month or £2,490/year. Enterprise: custom.",
    pricingCaveat: "A 14-day trial is advertised. Confirm users, refresh frequency, export and integration scope.",
    bestFor: "UK suppliers that want notice alerts plus incumbent and likely renewal context.",
    notFor: "Teams seeking bid-writing software or an official submission portal.",
    caveat: "Renewal windows are derived from published award information and are not confirmed procurements.",
    evidenceLinks: [{ label: "TenderLedger pricing and scope", url: "https://tenderledger.co.uk/pricing" }],
  }),
  commercialRecord({
    slug: "bidlens", name: "BidLens", category: "tender-alerts",
    providerType: "Commercial UK tender-matching service", officialUrl: "https://bidlens.uk/",
    summary: "BidLens scores notices by sector, region, buyer, value and semantic relevance, then sends scheduled digests.",
    coverage: "The provider names Find a Tender, Contracts Finder, Sell2Wales and Public Contracts Scotland.",
    pricing: "Starter: £49/month. Pro: £99/month. Team: £199/month. Prices exclude VAT.",
    pricingCaveat: "Starter sends a weekly digest. Pro adds daily alerts and unlimited saved searches. Team adds API and webhook access. Ask about annual terms.",
    bestFor: "British SMEs wanting a visible breakdown of why a notice matched.",
    notFor: "Suppliers that require confirmed eTendersNI coverage.",
    caveat: "Coverage and scoring are provider-stated. Test important local and sector sources during evaluation.",
    evidenceLinks: [{ label: "BidLens pricing", url: "https://bidlens.uk/pricing" }, { label: "BidLens coverage", url: "https://bidlens.uk/" }],
  }),
  commercialRecord({
    slug: "scrymint", name: "Scrymint", category: "tender-alerts",
    providerType: "Commercial UK tender search and alert service", officialUrl: "https://scrymint.com/",
    summary: "Scrymint advertises free tender search and daily alerts, with buyer, supplier and award pages alongside discovery.",
    coverage: "The provider says it covers UK tender and award feeds, including Find a Tender, Contracts Finder and devolved portals.",
    pricing: "Free search and daily alerts are advertised. No public numeric paid price was found on the checked page.",
    pricingCaveat: "Confirm limits, paid features, source refresh frequency and future pricing before relying on the service.",
    bestFor: "Small suppliers testing a free UK search and alert product.",
    notFor: "Teams that need a long operating history or a published enterprise service level.",
    caveat: "This is a newer service. Exact source coverage and corpus depth have not been independently tested by Civensa.",
    evidenceLinks: [{ label: "Scrymint product and coverage", url: "https://scrymint.com/" }],
  }),
  commercialRecord({
    slug: "tenderai", name: "TenderAI", category: "tender-alerts",
    providerType: "Commercial UK semantic tender-alert service", officialUrl: "https://tenderai.uk/",
    summary: "TenderAI uses a supplier profile to label matches as bid, flag or skip and sends a short daily list.",
    coverage: "Find a Tender and Contracts Finder.",
    pricing: "Launch price: £99/month per profile, with the first month free. Free users receive five weekly matches.",
    pricingCaveat: "The provider describes this as a limited launch. Confirm renewal price, VAT, users and profile limits.",
    bestFor: "UK SMEs that mainly monitor the two central government sources.",
    notFor: "Suppliers requiring Scottish, Welsh, Northern Irish or specialist portal coverage.",
    caveat: "The product covers two named feeds. Qualification labels are provider-generated aids, not buyer decisions.",
    evidenceLinks: [{ label: "TenderAI product and launch pricing", url: "https://tenderai.uk/" }],
  }),
  commercialRecord({
    slug: "tender-alerts-uk", name: "Tender Alerts UK", category: "tender-alerts",
    providerType: "Commercial UK tender search and alert service", officialUrl: "https://tenderalerts.uk/",
    summary: "Tender Alerts UK offers structured search, saved searches and weekday emails for one user.",
    coverage: "Find a Tender, Contracts Finder, Public Contracts Scotland and Sell2Wales.",
    pricing: "£109/month or £1,099/year. A seven-day trial is advertised.",
    pricingCaveat: "The trial converts automatically according to the provider. The checked plan lists one user and up to 50 alerts.",
    bestFor: "An individual UK bid or business-development user wanting four national sources.",
    notFor: "Teams that require eTendersNI, collaborative workflow or unlimited profiles.",
    caveat: "The provider describes keyword and structured filtering rather than semantic qualification.",
    evidenceLinks: [{ label: "Tender Alerts UK pricing and scope", url: "https://tenderalerts.uk/" }],
  }),
  commercialRecord({
    slug: "tendarix", name: "Tendarix", category: "tender-alerts",
    providerType: "Commercial UK tender and bid platform", officialUrl: "https://tendarix.com/",
    summary: "Tendarix advertises tender search, alerts, qualification, buyer intelligence, renewals, bid drafting and data access.",
    coverage: "The provider names all five national UK portals, TED and more than 400 buyer portals.",
    pricing: "Advertised as free for everyone, with no payment card and no trial limit.",
    pricingCaveat: "Confirm any fair-use limits, future commercial model, support terms and API conditions before adoption.",
    bestFor: "Suppliers willing to test a new broad-feature platform at no stated charge.",
    notFor: "Teams that need a proven operating history, contracted service levels or independently verified coverage.",
    caveat: "This is a new service with unusually broad free and unlimited claims. Audit known notices and exports before relying on it.",
    evidenceLinks: [{ label: "Tendarix product, sources and pricing claim", url: "https://tendarix.com/" }],
  }),
  commercialRecord({
    slug: "cleantender", name: "CleanTender", category: "tender-alerts",
    providerType: "Commercial soft-facilities-management tender platform", officialUrl: "https://cleantender.co.uk/",
    summary: "CleanTender focuses discovery and qualification on cleaning, security, grounds, waste and catering contracts.",
    coverage: "Find a Tender and Contracts Finder, according to the provider.",
    pricing: "Browsing and profile tools are advertised as free. Pro is listed at £99/month.",
    pricingCaveat: "Confirm VAT, drafting allowance, notice history, user limits and renewal terms.",
    bestFor: "UK soft-facilities-management suppliers that want a sector-specific view.",
    notFor: "Suppliers outside the supported sectors or those needing devolved-source coverage.",
    caveat: "This is a category-limited product using two named feeds, not a complete UK market database.",
    evidenceLinks: [{ label: "CleanTender product and plans", url: "https://cleantender.co.uk/" }],
  }),
  commercialRecord({
    slug: "contracts-advance", name: "Contracts Advance", category: "tender-alerts",
    providerType: "Commercial UK tender and contract-intelligence service", officialUrl: "https://contractsadvance.co.uk/",
    summary: "Contracts Advance provides tailored tender alerts, with higher plans adding renewals, research and market analysis.",
    coverage: "The provider says it monitors open public-procurement portals but does not publish a complete named-source list.",
    pricing: "Search: £1,399/year. Discover: £2,099/year. Explore: £2,999/year. Prices exclude VAT.",
    pricingCaveat: "Plans are annual. Confirm users, profiles, source coverage, onboarding and multiyear terms.",
    bestFor: "Established UK suppliers wanting alerts and progressively deeper contract intelligence.",
    notFor: "Small suppliers looking for a monthly self-serve entry plan.",
    caveat: "The broad source statement needs source-by-source testing against the portals that matter to your market.",
    evidenceLinks: [{ label: "Contracts Advance pricing", url: "https://contractsadvance.co.uk/pricing/" }, { label: "Contracts Advance product", url: "https://contractsadvance.co.uk/" }],
  }),
  commercialRecord({
    slug: "bidscout", name: "BidScout", category: "tender-alerts",
    providerType: "Commercial UK and EU tender and bid platform", officialUrl: "https://www.bidscout.co.uk/",
    summary: "BidScout advertises alerts, bid or no-bid support, writing, awards and contract-renewal tools.",
    coverage: "The provider describes UK and EU coverage but does not expose a complete named-source list on its public pricing page.",
    pricing: "Starter trial, Professional and Enterprise tiers are shown. No public numeric price was found.",
    pricingCaveat: "The Starter tier advertises a seven-day trial without a card. Request source, user, message and renewal details with the quote.",
    bestFor: "Bid teams willing to evaluate discovery, writing and market features together.",
    notFor: "Buyers who need transparent numeric pricing before a sales conversation.",
    caveat: "Coverage, AI-writing and renewal claims require account-level testing.",
    evidenceLinks: [{ label: "BidScout plans", url: "https://www.bidscout.co.uk/pricing" }],
  }),
  commercialRecord({
    slug: "mercell-tender-discovery", name: "Mercell Tender Discovery", category: "tender-alerts",
    providerType: "Commercial European tender-discovery platform", officialUrl: "https://info.mercell.com/en-gb/suppliers/tender-discovery/",
    summary: "Mercell Tender Discovery offers European opportunity search, alerts, summaries and early or below-threshold signals.",
    coverage: "European coverage including the UK. The checked page does not publish a complete UK source list.",
    pricing: "No public numeric price found. A 14-day trial is advertised.",
    pricingCaveat: "Ask for countries, UK portals, users, data history, renewal signals, integrations and contract term.",
    bestFor: "Larger suppliers comparing opportunities across several European markets.",
    notFor: "A UK-only SME that wants a simple published monthly price.",
    caveat: "UK source coverage and price are opaque on the public page. Test required portals during the trial.",
    evidenceLinks: [{ label: "Mercell Tender Discovery", url: "https://info.mercell.com/en-gb/suppliers/tender-discovery/" }],
  }),
  commercialRecord({
    slug: "jorpex", name: "Jorpex", category: "tender-alerts",
    providerType: "Commercial global tender-monitoring service", officialUrl: "https://jorpex.com/",
    summary: "Jorpex monitors international procurement sources and provides multilingual summaries, matching and email or Slack alerts.",
    coverage: "The provider names more than 50 global sources, including Find a Tender, Contracts Finder, TED and SAM.gov.",
    pricing: "Starter: $49/month. Pro: $149/month. Enterprise: custom. A 14-day trial and 35 percent annual saving are advertised.",
    pricingCaveat: "Confirm currency, taxes, UK devolved sources, alert volume, users and API access.",
    bestFor: "Suppliers monitoring opportunities in the UK and other countries.",
    notFor: "Teams requiring complete national and devolved UK portal coverage.",
    caveat: "The named source list does not establish full UK coverage.",
    evidenceLinks: [{ label: "Jorpex pricing", url: "https://jorpex.com/pricing/" }, { label: "Jorpex source scope", url: "https://jorpex.com/" }],
  }),
  commercialRecord({
    slug: "open-opportunities-alerts", name: "Open Opportunities", category: "tender-alerts",
    providerType: "Commercial global tender and contract-data platform", officialUrl: "https://openopps.com/",
    summary: "Open Opportunities provides global tender alerts, contract search, expiry data and paid API access.",
    coverage: "The provider claims more than 900 sources across more than 180 countries.",
    pricing: "Solo: £120 per user each month, billed £1,440 yearly. Team: £259 per team each month, billed £3,108 yearly. API: from £5,000/year.",
    pricingCaveat: "A seven-day trial without a card is advertised. Confirm team users, source countries, exports and renewal terms.",
    bestFor: "International tender teams or data users that need more than UK-only feeds.",
    notFor: "A small UK supplier seeking a low-cost national alert product.",
    caveat: "The global source count is provider-stated. Test the exact countries and UK portals you need.",
    evidenceLinks: [{ label: "Open Opportunities pricing", url: "https://openopps.com/pricing/" }],
  }),
  commercialRecord({
    slug: "tender-radar", name: "Tender Radar", category: "tender-alerts",
    providerType: "Emerging global tender-alert platform", officialUrl: "https://tenderradar.io/",
    summary: "Tender Radar advertises AI scoring, summaries, email or Slack alerts and data access across a small set of global sources.",
    coverage: "The provider lists 14 sources. Contracts Finder is the named UK source on the checked page.",
    pricing: "Waitlist pricing: Starter €79/month. Pro €149/month. Enterprise: custom.",
    pricingCaveat: "The product is on a waitlist. Treat prices and launch scope as provisional.",
    bestFor: "Teams exploring a cross-border alert tool and willing to test a prelaunch service.",
    notFor: "UK suppliers needing established or comprehensive national coverage now.",
    caveat: "This is a waitlist product with one named UK source. Do not treat it as a full UK market feed.",
    evidenceLinks: [{ label: "Tender Radar waitlist pricing", url: "https://tenderradar.io/pricing" }],
  }),
] as const;

export const tenderAlertRecords: readonly VendorRecord[] = tenderAlertBaseRecords.map((record) => {
  const normalized = tenderAlertResearchBySlug[record.slug];
  if (!normalized) throw new Error(`Missing normalized tender-alert research for ${record.slug}`);
  return { ...record, normalized, lastChecked: normalized.researchedAt };
});
